# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "multicross_compilation",
    # srcs = ["source files"],
    # copts = [],
    # deps = ["libraries to be linked"],
)