# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
    name = "dev",
    srcs = [
        "Developer.h",
        "IHuman.h",
    ],
    deps = ["//project/lib:libdev"],
    visibility = ["//project:__pkg__"]
)